# Site information
site_name: Beyond LaTeX Templates
site_url: https://hantang.github.io/latex-templates/
site_author: hantang
site_description: "Awesome latex* templates and beyond..."
copyright: Copyright &copy; 2023-2024 Hantang
repo_name: latex-templates
repo_url: https://github.com/hantang/latex-templates

# Theme
theme:
  name: material
  # custom_dir: overrides
  language: "zh"
  favicon: assets/favicon.ico
  icon:
    logo: simple/latex
    repo: fontawesome/brands/square-github
  font:
    text: Open Sans, Helvetica Neue, Roboto, sans-serif, serif
    code: Fira Mono, Fira Code, Roboto Mono, monospace
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_truly_sane_lists
  - tables
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/src/tablesort.min.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/dist/sorts/tablesort.date.min.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/dist/sorts/tablesort.number.min.js
  - assets/js/tablesort.js

  # - https://code.jquery.com/jquery-3.7.1.min.js
  # - https://cdn.datatables.net/2.0.2/js/dataTables.min.js
  # - https://cdn.datatables.net/plug-ins/2.0.2/i18n/zh.json
  # - assets/js/datatables.js

extra_css:
  # - https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.min.css
  - assets/css/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hantang

plugins:
  - search:
      lang:
        - en
        - zh
      separator: '[\s\-,:!=\[\]()"/\u200b]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - table-reader
  # - git-revision-date-localized
  - minify:
      minify_html: true

nav:
  - 主页: index.md
# START-NAV
# END-NAV
  # - 补充资料: 
  #   - resource/writing.md
  #   - resource/tutorial.md
  #   - resource/tools.md
